### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Fogh** [Fogh/AFWebViewController#1]
- [x] Add icons for back/forward buttons
- [x] Add Podspec
- [x] Add activity for "Open in Safari"
- [x] Add activity for "Open in Chrome"
- [ ] Boolean to toggle showing action buttons
- [ ] Support for adding UIActivities
- [x] Allow users to supply their own [`WKWebViewConfiguration`](https://developer.apple.com/library/IOs/documentation/WebKit/Reference/WKWebViewConfiguration_Ref/index.html#//apple_ref/swift/cl/WKWebViewConfiguration)

**Comment by Fogh** [comment]
Support for setting `WKWebViewConfiguration` added in #13
